In [43]:
import pandas as pd
import numpy as np

In [50]:
from sklearn.preprocessing import OneHotEncoder, LabelEncoder
df = pd.read_csv('train.csv', encoding='utf-8-sig')

df['신고일자'] = pd.to_datetime(df['신고일자'])
df.insert(1, '신고일자_월', df['신고일자'].dt.month)
df = df.drop('신고일자', axis=1)

In [57]:
c_df=pd.get_dummies(df[['신고일자_월','통관지세관부호','수입통관계획코드', '수입신고구분코드',
   '수입거래구분코드','수입종류코드','징수형태코드',
   '운송수단유형코드','반입보세구역부호']])

In [59]:
c_df

,신고일자_월,통관지세관부호,수입거래구분코드,수입종류코드,징수형태코드,운송수단유형코드,반입보세구역부호,수입통관계획코드_B,수입통관계획코드_C,수입통관계획코드_D,수입통관계획코드_E,수입통관계획코드_F,수입통관계획코드_H,수입통관계획코드_Z,수입신고구분코드_A,수입신고구분코드_B,수입신고구분코드_D,수입신고구분코드_E
0,1,40,15,21,11,40,4077180,0,1,0,0,0,0,0,1,0,0,0
1,1,20,15,21,11,10,4002001,0,1,0,0,0,0,0,0,1,0,0
2,1,10,94,21,11,40,15002001,0,0,0,0,1,0,0,0,1,0,0
3,1,20,15,21,11,10,4002001,0,1,0,0,0,0,0,0,1,0,0
4,1,40,15,21,11,10,2002079,0,0,0,0,1,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89614,11,20,11,21,14,10,2006033,0,0,0,1,0,0,0,0,1,0,0
89615,11,40,15,21,11,10,2002079,0,1,0,0,0,0,0,0,1,0,0
89616,11,20,15,21,11,40,4106006,0,0,1,0,0,0,0,0,1,0,0
89617,11,16,11,21,11,10,4077009,0,0,1,0,0,0,0,0,1,0,0
89618,11,20,15,21,11,10,4002001,1,0,0,0,0,0,0,0,1,0,0

In [60]:
c_df.columns

Index(['신고일자_월', '통관지세관부호', '수입거래구분코드', '수입종류코드', '징수형태코드', '운송수단유형코드',
       '반입보세구역부호', '수입통관계획코드_B', '수입통관계획코드_C', '수입통관계획코드_D', '수입통관계획코드_E',
       '수입통관계획코드_F', '수입통관계획코드_H', '수입통관계획코드_Z', '수입신고구분코드_A', '수입신고구분코드_B',
       '수입신고구분코드_D', '수입신고구분코드_E'],
      dtype='object')